### PR TITLE
Various fixes and updates

### PR DESCRIPTION
**Pull request by ramv**
1. Fixed typo in KafkaConsumerFactory.java
2. Updated KafkaProducerFactory.java http://kafka.apache.org/documentation.html#producerconfigs
3. Added test to verify that all settings are being populated correctly
4. Make the settings keys in yaml identical to settings keys in kafka
5. Added an example application that consumes a topic and produces on an other topic.

### CODE REVIEW

**Comment by ramv** [comment]
@nicktelford can you please review my pull request?

**Comment by nicktelford** [comment]
Could you do me favour and separate the example application out in to another branch and make a separate Pull Request for that? In general, it's best to submit smaller units of work as they're much easier to review in isolation.

**Comment by cbumgard** [comment]
+1 I'd love to see this pull-request merged

**Comment by nicktelford** [comment]
OK, so I've added support for Kafka 0.8 producers in c20e11e. Let me know if you have any issues.

**Pull request closed without merging**
